### PR TITLE
Add Timers menu in menu, add timer with vibration

### PR DESCRIPTION
**Pull request by realroot2185**
There are a lot of comments.
This PR should be reviewed.
Button to edit the timer count could be added.

### CODE REVIEW

**Comment by realroot2185** [comment]
Too many things and personal changes.

**Comment by lulf** [comment]
@realroot2185 This looks good, I just haven't had time to review it properly yet. I'd be happy to add it.

**Comment by realroot2185** [comment]
It would be nice to have a button when the timer is running, so when TimerState in watchful-ui/src/lib.rs is shown.

Vibrator name could be improved.

I added personal colors changes.
In Settings->Firmware the button should be lowered a little.

**Comment by realroot2185** [comment]
I think that something to handle submenus could be useful.
In main->timers pressing the button does not go back to main but draws again "timers".
Or it goes back to main.
I think that it should go back of one level for each press.

main->settings->firmware works fine because there is not state but timer needs one to update the value and then vibrate upon completion.
Not sure to how handle that.

**Pull request closed without merging**
